### ISSUE TITLE
[webpack-cli] Error: Prevent writing to file that only differs

### ISSUE THREAD

**Issue by nquangbaort** [themeselection/materio-vuetify-vuejs-laravel-admin-template-free#1]
I copy src from pro to your repo
bug : [webpack-cli] Error: Prevent writing to file that only differs in casing or query string from already written file.
This will lead to a race-condition and corrupted files on case-insensitive file systems.
You can help me?

**Comment by jd-solanki** [comment]
Hi,

Thanks for getting in touch. Have you purchased our pro version?

Have you tried restarting the server?

Awaiting your response.

**Comment by nquangbaort** [comment]
I buyed Pro full-version.
i fixed issue, 
thanls you <3
