### ISSUE TITLE
Vue error

### ISSUE THREAD

**Issue by lokutus24** [themeselection/materio-vuetify-vuejs-laravel-admin-template-free#3]
### Steps to reproduce

hello,

i try to install this theme, but i got some issues and it works not fine.
[https://ibb.co/H4c7FQp](url)

### What is expected?

i'd like to login into dashboard.

### What is actually happening?

i can not load dashboard due vue error.

**Comment by alokVishu** [comment]
Hello @lokutus24,

Please let me know the steps to reproduce the same. Also, try to download the fresh package and install the package using the yarn package manager.

Awaiting your reply.

~Regards
